### ISSUE TITLE
Invalid query error with latest provider

### ISSUE THREAD

**Issue by heldersepu** [terraform-providers/terraform-provider-datadog#259] opened 2019-07-13 01:41 UTC
### Terraform Version
0.11.14

### Affected Resource(s)
- datadog_monitor

### Terraform Configuration Files
```hcl
provider "datadog" {
  api_key = "abc123"
  app_key = "def456"
}

resource "datadog_monitor" "test" {
  name    = "test"
  message = "test"
  query   = "avg(last_1h):anomalies(avg:aws.s3.5xx_errors{bucketname:abc}, 'basic', 2, direction='above') >= 1"
  type    = "query alert"

  evaluation_delay    = 900
  no_data_timeframe   = 120
  renotify_interval   = 0
  include_tags        = false
  require_full_window = false

  thresholds {
    critical          = 1
    critical_recovery = 0.9
    warning           = 0.95
    warning_recovery  = 0.85
  }
}
```

### Expected Behavior
The monitor should be created

### Actual Behavior
API error 400 Bad Request: {"errors":["The value provided for parameter 'query' is invalid"]}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This same code works fine on older versions of the provider
- Working version:
> https://github.com/terraform-providers/terraform-provider-datadog/tree/a650e8b784d84a26ebbe6e4f71e19b057e1fc13c

- Broken latest:
> https://github.com/terraform-providers/terraform-provider-datadog/tree/d9f14f8469ca3bf825ba0a39317975a3bd01d150

**Comment by zioproto** [comment] 2019-07-13 06:54
Hello @heldersepu ,
thanks for the report of the issue
Could you please specify the exact version numbers for the providers that are working and that are not working.
thank you

**Comment by heldersepu** [comment] 2019-07-13 12:32
> Hello @heldersepu ,
> thanks for the report of the issue
> Could you please specify the exact version numbers for the providers that are working and that are not working.
> thank you
Links added for the commits tested

**Comment by heldersepu** [comment] 2019-07-14 01:38
I managed to narrow down to:
https://github.com/terraform-providers/terraform-provider-datadog/commits/11c6e0071372241431e76f5edd83f6bcd5d3bcb5 
that is the commit that breaks the provider, @enbashi any idea what could have gone wrong?

**Comment by heldersepu** [comment] 2019-07-14 02:11
Looking at the json that is posted to the API, I notice that the broken version is sending: 
`"period": null` and in some other cases `"threshold_windows": {},`
The API does not like that!  maybe a problem with the go-datadog-api ?

**Comment by enbashi** [comment] 2019-07-15 10:59
My commit includes updating to the latest version of the client library at the time so it's possible that your issue is caused by a bug there. If that's the case and you can reproduce using the client library, I suggest you file an issue in https://github.com/zorkian/go-datadog-api.

**Comment by bkabrda** [comment] 2019-07-15 12:34
This bug fixed by #260, so I'm closing this issue.

**Closed by bkabrda** 2019-07-15 12:34 UTC

**Comment by heldersepu** [comment] 2019-07-15 12:55
> This bug fixed by #260, so I'm closing this issue.

I thought that me adding a comment on the PR:
`This fixes issue #259` will automatically close the issue once merged

**Comment by bkabrda** [comment] 2019-07-15 12:58
@heldersepu I think you'd actually need to use `fixes #259`, the added word `issue` probably made Github not recognize this (guessing here).

**Comment by heldersepu** [comment] 2019-07-15 13:04
Dang! two words that's cold!
they should have a few "synonyms" to that, 🤔   I wonder if they allow PRs

**Comment by heldersepu** [comment] 2019-07-15 13:18
Found the article:
https://help.github.com/en/articles/closing-issues-using-keywords
Yes there are synonyms but only `keyword + #[issue]`
