### ISSUE TITLE
After applying without setting the precision parameter, the value of 0 is set on the timeboard side of datadog

### ISSUE THREAD

**Issue by yutachaos** [terraform-providers/terraform-provider-datadog#134] opened 2018-12-05 10:31 UTC
After applying without setting the precision parameter, the value of 0 is set on the timeboard side of datadog

### Terraform Version
- Terraform v0.11.8
- datadog provider 1.4
### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_timeboard

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "datadog_timeboard" "test" {
  description = "test"
  "graph" {
    "request" {
      q = "avg:aws.elb.httpcode_elb_5xx{*}.as_count()"
    }
    title = "A dashboard with memory info."
    viz = "heatmap"
  }
  title = "test"
}
```

### Expected Behavior
When the value of precision is not set in tf file, the value of zero is sent to datadog api.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
```
 terraform apply --target datadog_timeboard.test
datadog_timeboard.test: Refreshing state... (ID: 1010518)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ datadog_timeboard.test
      graph.0.precision: "0" => ""
```

2. Retry `terraform apply`

```
 terraform apply --target datadog_timeboard.test
datadog_timeboard.test: Refreshing state... (ID: 1010518)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ datadog_timeboard.test
      graph.0.precision: "0" => ""
```

**Comment by nmuesch** [comment] 2019-06-03 18:29
Hey @yutachaos Thanks for the detailed issue report, apologies for the delay here. I took a look into this but have been unable to reproduce this issue with the provided config. Are you still experiencing this issue?

**Comment by nmuesch** [comment] 2019-08-13 14:49
Hey @yutachaos As we weren't able to reproduce I'll go ahead and close this issue for now. Please do let me know if you continue to experience an issue with this and we'll be happy to open this back up.

**Closed by nmuesch** 2019-08-13 14:49 UTC
