### ISSUE TITLE
Add Dashboard List Support

### ISSUE THREAD

**Issue by lexrj** [terraform-providers/terraform-provider-datadog#223] opened 2019-06-04 02:50 UTC
### Terraform Version
terraform 0.12

### Affected Resource(s)
Add a new one please datadog_dashboard_list

### Expected Behavior
Dashboard lists are an important way to organize dashboards, and help mitigate the risk of dashboard faves being lost when a dashboard is destroyed and recreated. Providing a way to create a dashboard list and add created dashboards to it would be extremely useful.

### References
https://docs.datadoghq.com/api/?lang=bash#dashboard-lists

**Comment by bkabrda** [comment] 2019-07-24 09:59
Thanks for opening this issue. It is a duplicate of #63, so I'll close it - feel free to follow #63.

**Closed by bkabrda** 2019-07-24 09:59 UTC

**Comment by lexrj** [comment] 2019-07-24 14:08
Thanks, I had trouble finding that ticket before for some reason.
