### ISSUE TITLE
Cannot apply screenboards, error: "json: cannot unmarshal string..."

### ISSUE THREAD

**Issue by kwolff-chwy** [terraform-providers/terraform-provider-datadog#350] opened 2019-10-25 17:02 UTC
Hello,

I was trying to solve an issue with a new dashboard widget that was giving me this error:
**Error: datadog_screenboard.sfw_screenboard: widget.14.tile_def.0.request.0: invalid or unknown key: apm_query**

It turned out that I was using provider v1.4 and that didn't have the functionality yet.  So I tried to upgrade to the latest version (2.5) and suddenly I couldn't do an apply for any dashboard that I have.  Each one fails with this error:
**json: cannot unmarshal string into Go struct field Screenboard.height of type int**

I backed up through the whole list of versions and it seems that this bug was introduced in v2.3.  Before that, I just get the original "apm_query" error for the one dashboard.  I have backed up to 2.2 for now, but sadly the apm_query functionality is newer than that. :(

### Terraform Version
Terraform v0.11.10
provider.datadog v2.5.0

### Affected Resource(s)
- datadog_screenboard
- possibly others but I haven't tested

### Terraform Configuration Files
It happens with all my screenboards so I don't think posting them will be useful as of now.

### Debug Output
https://gist.github.com/kwolff1/1beba354534b2fff6ea38d03f1d78a99

### Expected Behavior
Applied changes to one dashboard.  (No others have been modified since my last successful apply.)

### Actual Behavior
The error **json: cannot unmarshal string into Go struct field Screenboard.height of type int** for every single dashboard in the folder.

### Steps to Reproduce
`terraform apply`

### References
- [this looks similar](https://github.com/terraform-providers/terraform-provider-datadog/issues/105)

**Comment by kwolff1** [comment] 2019-10-25 19:58
CORRECTION: After commenting out the widget that I can't apply, I found that this happens with versions much older than 2.2.  In fact, 1.4 is the only version it fully works with.  In 1.5, it causes a crash, and the error I posted above first appears in 1.6.

**Comment by nmuesch** [comment] 2019-10-31 19:32
Hey, @kwolff1 Apologies that you're encountering this issue. I believe this may be a dupe of https://github.com/terraform-providers/terraform-provider-datadog/issues/133

I don't currently have an update there but it looks like there are some workarounds on that thread if they can be of help.

**Comment by kwolff1** [comment] 2019-10-31 21:13
Thanks @nmuesch .  I found my own workaround, actually, which involved deleting one screenboard from Datadog, creating a new local directory, moving the one screenboard into it, having the provider be v2.5 in that directory, and running 'apply' again (which creates it as a new screenboard).

Unfortunately, this resulted in a _different_ problem where it doesn't seem to understand the X and Y coordinate values properly, and everything is squished into a few overlapping rows of widgets.  Oy!  Alas, I do not have time right now to report that as a separate issue or investigate further.

**Comment by gzussa** [comment] 2020-06-20 07:28
Closing this issue since there seems to be a workaround. Also `screenboard` and `timeboard` resources are being deprecated in favor of the `dashboard` resource.

**Closed by gzussa** 2020-06-20 07:28 UTC
Labels: bug
