### ISSUE TITLE
datadog_dashboard manage_status_definition displays 'No results found'

### ISSUE THREAD

**Issue by 0x646e78** [terraform-providers/terraform-provider-datadog#454] opened 2020-03-18 06:44 UTC
### Terraform Version
Terraform 0.12.21
Datadog provider 2.7.0

### Affected Resource(s)
- datadog_dashboard
- - manage_status_definition.

### Terraform Configuration Files
```hcl
resource "datadog_dashboard" "test" {
  title       = "Testing Dashboard Import Bug"
  description = "Monitor Summary should populate"
  layout_type = "free"
  is_read_only   = true

  widget {
    manage_status_definition {
      summary_type = "monitors"
      query = "tag:domain:cnp env:prod"
      sort = "status,asc"
      display_format = "counts"
      color_preference = "background"
      hide_zero_counts = true
      title = "CNP Health Summary"
      title_size = "13"
      title_align = "left"
      show_last_triggered = false
    }
    layout = {
      x = 26
      y = 0
      width = 62
      height = 16
    }
  }
}

```

### Debug Output
https://gist.github.com/0x646e78/186c519f53a9fd33cfbd7d75ddea7152

### Panic Output
n/a

### Expected Behavior
A dashboard is created with a Monitor Summary widget which displays a count.

### Actual Behavior
The Monitor Summary widget is created but reports *No results found*, but if I _Edit Widgets_ and then enter the _2) Search_ (i.e. query) field and change anything it works. Note that all I need to do is delete a character and then enter the same one, and it will populate a digit, so it's not that my query is wrong.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Works fine using the API directly to create the same thing, with this request body:
```
{
  "title": "TESTING API",
  "description": "Monitor Summary should populate",
  "layout_type": "free",
  "is_read_only": false,
  "widgets": [
    {
      "definition": {
        "type": "manage_status",
        "query": "tag:domain:cnp env:prod",
        "summary_type": "monitors",
        "sort": "status,asc",
        "display_format": "counts",
        "color_preference": "background",
        "hide_zero_counts": true,
        "show_last_triggered": false,
        "title": "CNP Health Summary",
        "title_size": "13",
        "title_align": "left"
      },
      "layout": {
       "x": 26,
       "y": 0,
       "width": 62,
       "height": 16
      }
    }
  ]
}
```
https://docs.datadoghq.com/api/?lang=bash#create-a-dashboard

### References
Not that I know of.

**Comment by gruebel** [comment] 2020-04-02 10:10
Same problem here! There was a deprecation in #403 of two parameters `count` and `start`. And it looks like the `count` parameter is still needed somehow. Just change your resource definition to
```
resource "datadog_dashboard" "test" {
  title       = "Testing Dashboard Import Bug"
  description = "Monitor Summary should populate"
  layout_type = "free"
  is_read_only   = true

  widget {
    manage_status_definition {
      summary_type = "monitors"
      query = "tag:domain:cnp env:prod"
      sort = "status,asc"
      display_format = "counts"
      color_preference = "background"
      hide_zero_counts = true
      title = "CNP Health Summary"
      title_size = "13"
      title_align = "left"
      show_last_triggered = false
      count = 50
    }
    layout = {
      x = 26
      y = 0
      width = 62
      height = 16
    }
  }
}
```
and it should work again.

**Comment by bkabrda** [comment] 2020-04-28 09:25
Hi, thanks for the issue report! I can reproduce this. The issue seems to be that the due to a quirk in the Terraform SDK, an integer value inside a nested map is always seen internally as `0` even if the field is not specified in the TF config at all.

It seems that the easiest solution that we can do is set a default value for `count` to `50` (which is basically what the web UI does). I'm discussing this with the monitors team to verify that this is the correct approach. If so, it should be easy to fix.

**Comment by bkabrda** [comment] 2020-05-13 13:50
Fixed in https://github.com/terraform-providers/terraform-provider-datadog/pull/514

**Closed by bkabrda** 2020-05-13 13:50 UTC
Labels: bug
