### ISSUE TITLE
Timeboard graph fields ignored

### ISSUE THREAD

**Issue by miguelaferreira** [terraform-providers/terraform-provider-datadog#142] opened 2019-01-08 10:19 UTC
I'm reporting reproducible behaviour of the provider that ignores configuration fields that are set in terraform and wants to set them over and over. Also defaults to certain fields that are not set in terraform keep being reported as changes to be applied with every plan.

It is likely that some of the things I'm reporting here have been reported in other issues, but I'll still keep them here together with the code to reproduce it.

### Terraform Version
```
Terraform v0.11.11
+ provider.datadog v1.6.0
```

### Affected Resource(s)
- datadog_timeboard

### Terraform Configuration Files
```hcl
variable "datadog_api_key" {
  default = ""
}

variable "datadog_app_key" {
  default = ""
}

provider "datadog" {
  api_key = "${var.datadog_api_key}"
  app_key = "${var.datadog_app_key}"
}

resource "datadog_timeboard" "request_type_ignored" {
  description = "Ignored fields in dashboard config DataDog"

  "graph" {
    "request" {
      q         = "avg:system.cpu.user{*}"
      type      = "line"
      extra_col = true
    }

    title = "Query value graph"
    viz   = "query_value"
  }

  "graph" {
    autoscale = true

    "request" {
      q         = "avg:system.cpu.user{*}"
      type      = "line"
    }

    title = "Top list graph"
    viz   = "toplist"
  }

  graph {
    autoscale = true

    "request" {
      q         = "avg:system.cpu.user{*}"
      type      = "bars"

      aggregator = "avg"

      style {
        palette      = "orange"
        palette_flip = false
      }
    }

    title = "Timeseries graph"
    viz   = "timeseries"
  }

  title       = "Ignored fields in dashboard config DataDog"
}
```

### Debug Output
https://gist.github.com/miguelaferreira/9397dce94aa9c0f8deb79d9833917c34

### Expected Behavior
At first run terraform should create the dashboard and subsequent terraform runs should not produce any changes.

### Actual Behavior
At first run terraform should create the dashboard and subsequent terraform runs always present changes to graph request `type`, `extra_col` and `precision`.
```
  ~ datadog_timeboard.request_type_ignored
      graph.0.precision:                    "2" => ""
      graph.0.request.0.extra_col:          "" => "1"
      graph.0.request.0.type:               "" => "line"
      graph.1.autoscale:                    "false" => "true"
      graph.1.request.0.type:               "" => "line"
      graph.2.autoscale:                    "false" => "true"
      graph.2.request.0.aggregator:         "" => "avg"
      graph.2.request.0.style.%:            "1" => "2"
      graph.2.request.0.style.palette_flip: "" => "0"

```

Also when I remove the type field from the request blocks terraform offers (and keeps offering) to set it anyway.
Code change:
```
(...)
  "graph" {
    "request" {
      q         = "avg:system.cpu.user{*}"
#      type      = "line"
      extra_col = true
    }

    title = "Query value graph"
    viz   = "query_value"
  }

  "graph" {
    autoscale = true

    "request" {
      q         = "avg:system.cpu.user{*}"
#      type      = "line"
    }

    title = "Top list graph"
    viz   = "toplist"
  }
(...)
```

Terraform plan:
```
  ~ datadog_timeboard.request_type_ignored
      (...)
      graph.0.request.0.type:               "" => "line"
      graph.1.autoscale:                    "false" => "true"
      graph.1.request.0.type:               "" => "line"
      (...)
```
Which means that no matter what I do tho the `type` field the provider will always want to change it.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. `terraform plan` 

### References
See this [repo branch](https://github.com/miguelaferreira/terraform-datadog-bugs/tree/request-type-ignored-when-graph-type-not-timeseries) where I have placed the code to reproduce this issue.

**Comment by nmuesch** [comment] 2019-06-03 19:34
Hey @miguelaferreira Apologies for the delay here. I'm currently looking into this issue. (Thanks for the details and example config to reproduce) So far it looks like the `type` parameter issue may be solved? I can't reproduce terraform wanting to change that config, are you still experiencing an issue there? 

I can confirm the provider wanting to change the `precision` attribute on successive runs, and will investigate that.

**Comment by miguelaferreira** [comment] 2019-06-05 08:56
Hi @nmuesch. Thanks for picking this up. It seems the issue with the `type` parameter because I cannot reproduce it either on:
```
Terraform v0.11.13
+ provider.datadog v1.9.0
```

I still do see issues with `prevision` and `request.*.extra_col` and re-applying a plan.
```
Terraform will perform the following actions:

  ~ datadog_timeboard.request_type_ignored
      graph.0.precision:           "2" => ""
      graph.0.request.0.extra_col: "" => "1"
```

**Comment by nmuesch** [comment] 2019-06-05 14:55
Thanks for that confirmation! Glad to hear we're part of the way there 😄 I'll take a look into the precision and extra_col diff.

**Comment by nmuesch** [comment] 2019-06-07 14:40
Hey @miguelaferreira Just wanted to let you know that we just merged in https://github.com/terraform-providers/terraform-provider-datadog/pull/228 that should address the spurious diff when not explicitly setting the `precision` value for widgets. Theres still the `extra_col` field I have to look into, but one step closer.

**Comment by bkabrda** [comment] 2019-06-11 07:58
So it seems that `extra_col` can only be used for `change` widgets and the API ignores it for other widgets. This results in TF sending it every time and API never returning it, thus the non-empty plan produced every time. Additionally, the only allowed value is "present" or empty value. I'll add more validation to make sure the provider checks this and thus prevents these errors.

**Comment by nmuesch** [comment] 2019-06-14 20:37
I'll go ahead and close out this issue for now as it looks like the spurious diff issues should be resolved with the next Datadog Terraform Provider release! On a related note, we've also been working on fixing up the acceptance tests, which should no longer have failures after a couple open PRs are merged 💚 

Please do let us know if there are any further issues on this!

**Closed by nmuesch** 2019-06-14 20:37 UTC
