### ISSUE TITLE
New 10m default for no_data_timeframe causes permanent diff when notify_no_data is not explicitly set

### ISSUE THREAD

**Issue by 2rs2ts** [terraform-providers/terraform-provider-datadog#369] opened 2019-12-16 23:34 UTC
### Terraform Version

```
Terraform v0.11.8
+ provider.datadog v2.5.0
+ provider.pagerduty v1.4.1

Your version of Terraform is out of date! The latest version
is 0.12.18. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `datadog_monitor`

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "mymonitor" {
  name  = "myname"
  query = "max(last_1m):max:haproxy.frontend.session.pct by {datacenter,host} > 70"

  type = "query alert"

  message = "mymessage"

  thresholds {
    critical = 70
    warning  = 50
  }

  new_host_delay = 300

  tags = ["mytag"]
}
```

### Debug Output
Going to omit this if possible. I do not want to give away any sensitive info. Reproducing this should be pretty easy though.

### Panic Output
N/A

### Expected Behavior
Since `notify_no_data` is not set and its default is false, `no_data_timeframe` should not show up on any diffs.

### Actual Behavior
This diff persists:

```
  ~ module.mymodule.module.mysubmodule.datadog_monitor.mymonitor
      no_data_timeframe:              "0" => "10"
```

Explicitly setting `no_data_timeframe = 0` makes this diff go away.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### Important Factoids
N/A probably

### References
- https://github.com/terraform-providers/terraform-provider-datadog/pull/212 seems to be the cause of this

**Comment by 2rs2ts** [comment] 2019-12-16 23:40
Oh I just discovered something, I think if you explicitly set `notify_no_data` this diff doesn't happen and datadog stores the 10 minutes in the UI even though it's set to not notify.

**Comment by xp-1000** [comment] 2020-01-14 16:03
Hello,

it seems to come from a recent API change from Datadog side.

It is true https://github.com/terraform-providers/terraform-provider-datadog/pull/212 is the (indirect) cause but this was not true when this has been implemented and merged.

In my opinion, Datadog should take care of testing and updating their own official provider when they change their API (or at least communicate on these changes before to allow us to anticipate).

**Comment by jurajseffer** [comment] 2020-01-14 16:25
When `notify_no_data` is set to `false`, setting `no_data_timeframe` to `0` gets rid of the permanent diff from the plan. There will be an initial difference in *old* and *new* monitors showed in the plan though.

**Comment by phillip-dd** [comment] 2020-01-15 13:44
Also seems related to https://github.com/terraform-providers/terraform-provider-datadog/issues/383.

**Comment by calebtote** [comment] 2020-01-17 17:16
> When `notify_no_data` is set to `false`, setting `no_data_timeframe` to `0` gets rid of the permanent diff from the plan. There will be an initial difference in _old_ and _new_ monitors showed in the plan though.

Interestingly, if you set it to `10`, the permanent diff remains.

**Comment by Arbakkinn** [comment] 2020-01-28 08:32
Upgrading the Datadog provider to 2.6.0 solved the issue for me.

See #384

**Comment by bkabrda** [comment] 2020-02-04 17:25
Hey @2rs2ts did 2.6.0 resolve the issue for you as well?

**Comment by bkabrda** [comment] 2020-02-06 14:43
Ok, since I can't reproduce this any more (using 2.6.0 provider version), I'm going to close this issue. Feel free to open a new issue if this still hits you. Thanks!

**Closed by bkabrda** 2020-02-06 14:43 UTC

**Comment by 2rs2ts** [comment] 2020-02-26 23:20
Hey folks, sorry that it took me a while to reply. Was really busy. I just confirmed that I don't see this issue anymore! Thanks a bunch.
