### ISSUE TITLE
Bug: datadog_monitor - after terraform apply, next apply says change datadog_monitor resource 

### ISSUE THREAD

**Issue by karpenkoKhAI** [terraform-providers/terraform-provider-datadog#166] opened 2019-03-25 07:50 UTC
### Terraform Version
Terraform v0.11.3
+ provider.datadog v1.7.0

### Affected Resource(s)
1. "datadog_monitor"

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "example" {
    name    = "..."
    type    = "..."
    query   = "..."
    message = "..."

    thresholds {
        critical = "..."
    }

    silenced {
        "*" = "${var.is_datadog_monitor_enabled}"
    }

    notify_no_data    = ...
    no_data_timeframe = "..."
    renotify_interval = "..."

    require_full_window = ...
}
```

### Debug Output
  ~ module.monitor.example
      silenced.%:      "0" => "1"
      silenced.*:      "" => "1"

### Expected Behavior
If variable is_datadog_monitor_enabled  is equal 0 or 1, next terraform apply says no changes. 

### Actual Behavior
If variable is_datadog_monitor_enabled (see above) is equal 0, next terraform apply says no changes. If  is_datadog_monitor_enabled is equal 1, next terraform apply says that has changed in datadog_monitor (see output).

### Steps to Reproduce
1. Create a test monitor
1. Set is_datadog_monitor_enabled = 1
1. terraform apply
1. After deploy resource, run terraform apply for check changes.

### References
1. https://github.com/terraform-providers/terraform-provider-datadog/issues/71
1. https://github.com/terraform-providers/terraform-provider-datadog/issues/41

**Comment by Phansa** [comment] 2019-03-29 23:18
I have seen the same issue (I looked into this around February of this year) and for things where we are setting silenced for multiple resources say like 50 at a time the whole terraform plan output is just filled with lines that are 
silenced.%: "0" => "1"
silenced.*: "" => "1"
and you need to manually scroll through it to find any actual changes. It's not scalable either say you were to create 1000+ resources at time all with a silenced field, you would have to scroll up through 1000+ lines of just
silenced.%: "0" => "1"
silenced.*: "" => "1"
to find what actual changes are going through. I would second that someone should look into this and fix it.

**Comment by ardrigh** [comment] 2019-05-02 02:15
Personally, I don't think this is a bug. Your code is not doing what Datadog expects the parameter to be set to. Terraform is correctly showing it as a change due to Datadog updating the value to match their system.

In Datadog, a monitor without the silenced value defaults to empty:
```json
	"options": {
		"silenced": {},
	}
```
If you silence a specific host, it adds those hosts:
```json
	"options": {
		"silenced": {
			"host:host.example.com": null,
			"host:host2.example.com": null
		},
	}
```

The wildcard option is **only** triggered when you mute the entire monitor:
```json
	"options": {
		"silenced": {
			"*": null
		},
	}
```
Note also that all of the key values are set to `null` not `0` or `1`.

**Comment by Phansa** [comment] 2019-05-13 03:23
The terraform provider expects and int so you cannot pass a null or empty string if that that is what the Datadog API expects. Setting the int value to -1 is the only way I know of to not mute the monitor. The use case is we want to be able to pass in a list and mute certain monitors from that list if they go off too much while we fix them and keep all other unmuted. If the Datadog API is expecting nulls and empty strings and not 0's / only integers then this provider should be updated to make it consistent with the behavior the API wants especially since there is no good way to mute monitors with the current syntax. IE the provider can take an empty string if you don't want to mute the monitor, null if you want to permanently mute or and integer value for muting it a set amount of time instead of only accepting ints right now.

**Comment by ardrigh** [comment] 2019-05-13 04:13
There is a specific provider for muting things. It's called `datadog_downtime`. 
https://www.terraform.io/docs/providers/datadog/r/downtime.html

Create a downtime using the Terraform provider (or do it manually). Use your on/off code to set the mute to be active/inactive. Set your downtime to relate to a specific monitor id value.

You should also ignore the silenced value in your monitors so they don't show as being changed:
```terraform
  lifecycle {
    ignore_changes = ["silenced"]
  }
```

**Comment by bkabrda** [comment] 2019-05-13 13:14
So here's my understanding of the issue:

The reproducer from the original issue report by @karpenkoKhAI works because:

* With setting the value to `0`, it mutes the monitor indefinitely.
* With setting the value to `1`, it actually mutes the monitor until time `1`, IOW 1st January 1970, 00:00:01. This is now always in the past, so it effectively unmutes the monitor.

The changes in `silenced` are seen on every plan/apply because the Datadog API doesn't return the muted scope if the end time is in the past (but it is still "muted" until that time).

The "correct" way to remove the mutes ATM is to just remove them from the Terraform config file. I do understand how this is not practical for the use cases described by @karpenkoKhAI as well as @Phansa. The solutions to this problem that I can see:

1. Ask the monitors team in Datadog to create a special value that would mean "not muted" and would always be explicitly returned by the API.
2. Do the above by returning mute times in the past (so effectively making the original reproducer work ok as-is).

I can definitely go talk to the Datadog monitors team about this, but I'd like to hear if you folks agree that this is fair. TBH I'd probably be leaning towards solution number 2, since that would be better for backwards compatibility and also it would allow people to leave past mute times in their TF config files until they needed to change them (and plan/apply would always be clean). WDYT?

**Comment by ardrigh** [comment] 2019-05-13 22:24
Personally I think it would be better to remove the `silenced` value from the monitors altogether as something users can specify, and improve the usability of specifying downtimes correctly.

**Comment by Phansa** [comment] 2019-05-14 12:58
I think the second solution could work and is better for backwards compatibility but the first solution would be better overall since you can clearly have a return value for not muted instead of the API just returning an empty string.

**Comment by platinummonkey** [comment] 2019-05-27 16:49
Chiming in here, but it’s probably better for this resource to ignore this option field as the downtime resource can modify it externally.

**Comment by nmuesch** [comment] 2019-06-11 14:29
Hey @karpenkoKhAI and everyone 👋 We just merged in this PR - https://github.com/terraform-providers/terraform-provider-datadog/pull/221 that should resolve the issue with the spurious diff on subsequent applies, as well as providing a special value of `-1` as the timestamp in your terraform config to tell the provider to unmute the scope. 

I'll go ahead and close this issue for now, as this will be released with the next version of the Datadog Provider. Please let me know if this continues to be an issue!

**Closed by nmuesch** 2019-06-11 14:29 UTC
