### ISSUE TITLE
datadog_synthetics_test does not output an id compatible with composite monitors

### ISSUE THREAD

**Issue by hmklabs-dclow** [terraform-providers/terraform-provider-datadog#205] opened 2019-05-16 01:04 UTC
### Terraform Version
Terraform v0.11.13
+ provider.datadog v1.9.0

### Affected Resource(s)
- datadog_synthetics_test

### Expected Behavior
```
resource "datadog_monitor" "service_health_check" {
  name  = "Service health check failed"
  type  = "composite"

  message = "A service has failed a health check"

  query = "${join(" || ", datadog_synthetics_test.service_health.*.id)}"
}
```

### Actual Behavior
Output ids are in the format `b59-spd-ua6` but it looks like the composite monitor expects a seven digit number.

**Comment by nmuesch** [comment] 2019-05-29 12:54
Hey @hmklabs-dclow Thanks for the issue report and terraform config. I was able to reproduce this and can confirm that this isn't possible today. That being said it's something we're looking into. I'll reach back out if there are any updates here.

**Comment by platinummonkey** [comment] 2019-05-30 14:41
`.monitor_id` is the correct correlation for synthetics resource mapping to it's synthetic monitor

**Comment by nmuesch** [comment] 2019-05-30 15:13
The monitor_id field isn't currently returned through the go api client, but it looks like thats currently being worked on.

**Comment by alksl** [comment] 2019-06-10 06:51
Datadog is now also returning the `monitor_id` and it's available in the API client https://github.com/zorkian/go-datadog-api/pull/243

**Comment by bkabrda** [comment] 2019-06-10 07:53
This was actually implemented in https://github.com/terraform-providers/terraform-provider-datadog/pull/222 (added `monitor_id` attribute of the synthetics tests). It will be part of next release of this provider. Closing this issue.

**Closed by bkabrda** 2019-06-10 07:53 UTC
