### ISSUE TITLE
Doesn't support Log Alert Monitor

### ISSUE THREAD

**Issue by geekeren** [terraform-providers/terraform-provider-datadog#148] opened 2019-01-30 10:46 UTC
Hi there, I create two monitors, one is created manually, the other is by terraform.

### Terraform Version
Terraform v0.11.11
+ provider.datadog v1.6.0

### Terraform Configuration Files
```hcl
resource "datadog_monitor" "return_404s" {
  name               = "LB returning 404s"
  type               = "log alert"
  message            = <<EOT
The threshold on this may need to be tweaked!

@pagerduty-EdgeLoadBalancer
EOT
  query = "logs(\"source:nginx AND @http.status_code:404\").index(\"main\").rollup(\"count\").last(\"5m\") > 5"

  thresholds {
    critical = 5
  }
  silenced {
    "*" =  false ## unmute or not
  }
}
```

When I edit the monitor, I expected to see:
### Expected Behavior

![Expected Behavior](https://user-images.githubusercontent.com/13082375/51976129-e2dc8600-24be-11e9-8c12-c47d79948730.png)

### Actual Behavior
but I saw the search query is empty:

![image](https://user-images.githubusercontent.com/13082375/51976170-fbe53700-24be-11e9-9f48-f21f79b2374a.png)

When I go to view page, the two monitors are the same:
![image](https://user-images.githubusercontent.com/13082375/51976684-46b37e80-24c0-11e9-8473-77778dbe8cd5.png)

**I am not sure whether is UI issues of datadog, or the log alert doesn't work at all**

**Comment by rsun-thoughtworks** [comment] 2019-05-05 09:12
I have the same problem.
To find the root cause of it, I read the source code of terraform-provider and the POST message when we save a monitor in datadog page.

I found out that the "AND"s are in `queryConfig.queryString` and terraform-provider does not support this property.

I suggest that datadog official team can fix this bug.

Thanks for your team and work with love.

**Comment by bkabrda** [comment] 2019-05-09 08:47
Hi everyone, I’ve raised this issue internally to our monitors team and they’ve acknowledged this is a bug and will work to fix it. I'll post an update here when there's some development on this.

**Comment by geekeren** [comment] 2019-05-09 10:26
> Hi everyone, I’ve raised this issue internally to our monitors team and they’ve acknowledged this is a bug and will work to fix it. I'll post an update here when there's some development on this.

Can I ask your team will fix the datadog or terraform datadog provider? Because I am trying to fix this by changing code of terraform-datadog-provider then create a PR?

**Comment by bkabrda** [comment] 2019-05-09 11:07
@geekeren they're still looking into it and trying to figure out what would be the best solution. ATM it's not been decided where the fix will be, so it can be either the provider, the datadog internal mechanisms or both. I'll keep updating this issue as situation develops. Thanks for your patience everyone!

**Comment by geekeren** [comment] 2019-05-09 12:35
#199 Here is a PR to fix this issue

**Comment by bkabrda** [comment] 2019-05-14 06:38
Thanks for the PR, I'll try to have a look during today.

**Comment by bkabrda** [comment] 2019-05-15 10:48
So after some discussion with the Datadog monitors team, it seems that the solution provided in #199 is correct short-term. In the long term, the monitors team will remove the need to add `query_config` and the log query will be parsed directly from the current `query` attribute (IOW, whenever this is fixed, we'll just revert #199 and things will continue working).

In terms of backwards compatibility, the monitors API will keep accepting (and silently ignoring) `query_config` for some time (which we'll make sure is long enough) after the fix explained above is implemented. That will make it safe for us to revert #199 and release new version that doesn't use it any more.

**Comment by bkabrda** [comment] 2019-05-15 11:56
The fixing PR was merged, I'm closing this issue.

**Closed by bkabrda** 2019-05-15 11:56 UTC

**Comment by bkabrda** [comment] 2019-06-05 11:26
Hey folks, for the record, the API now parses the query itself and so query_config is not required. As a result:

* I submitted PR#226 to revert PR#199 as it's no longer needed.
* The previously released datadog provider versions should work fine from now on.
