### ISSUE TITLE
Unexpected EOF 

### ISSUE THREAD

**Issue by AnnaWykes** [terraform-providers/terraform-provider-datadog#374] opened 2019-12-23 11:06 UTC
Hi,

I'm recreating a Datadog dashboard from the downloadable json available on the Datadog portal

Unfortunately, despite exactly matching the json I get an `unexpected EOF `  error every time I try to do terraform apply, on any widgets in my dashboard

Below I've provided the JSON and terraform for one widget 

JSON: 

>       {
>             "id": 4,
>             "definition": {
>                 "type": "query_value",
>                 "requests": [
>                     {
>                         "log_query": {
>                             "index": "main",
>                             "compute": {
>                                 "aggregation": "count"
>                             },
>                             "search": {
>                                 "query": "team:pace service:self-serve-refunds @mdc.errorCode:*"
>                             },
>                             "group_by": []
>                         },
>                         "aggregator": "avg"
>                     }
>                 ],
>                 "title": "Rejections Count",
>                 "title_size": "16",
>                 "title_align": "left",
>                 "autoscale": true,
>                 "precision": 0
>             }

TERRAFORM:

```
widget {
      query_value_definition {
        title = "Rejections Count"
        title_align = "left"
        title_size = "16"
        precision = 0

       request {
          log_query {
            index = "main"
            compute {
              aggregation = "count"
            },
            search {
              q = "team:pace service:self-serve-refunds @mdc.errorCode:*"
            }
          }
          aggregator = "avg"
        }

       }
      layout {
        x = "49"
        y = "0"
        width = "23"
        height = "15"
      }
    }
```

I have other dashboards and widgets working fine, the only obvious difference is the nested `log_query` and `compute` in the `request` in the new widgets I'm trying to create. In our other dashboards there is simply a `q` for the query

Please can someone tell me if I'm doing something wrong if if this is a bug 

I'm using terraform v0.11.14

**Comment by AnnaWykes** [comment] 2019-12-23 15:03
I've resolved the issue by changing `q` to `query`. We've used `q` everywhere else and it works fine

**Comment by bkabrda** [comment] 2020-02-04 17:10
Hmm, I can't reproduce this issue. I'm going to assume that it was just misconfiguration and close this issue, but please do open a new issue if you hit this again and paste the exact error for closer inspection. Thanks!

**Closed by bkabrda** 2020-02-04 17:10 UTC
