### ISSUE TITLE
PagerDuty api_token gets replaced every time - service objects being removed

### ISSUE THREAD

**Issue by ScOut3R** [terraform-providers/terraform-provider-datadog#303] opened 2019-08-28 01:36 UTC
Hi,

the `datadog_integration_pagerduty` resource tries to replace the `api_token` attribute every time I apply the plan.

I assume this causes the previously deployed `datadog_integration_pagerduty_service_object` resources to be removed from Datadog, while they remain in the terraform state object. This causes the next run to fail, because during state refresh the provider complains that the service mapping is missing.

### Terraform Version
0.12.6

### Affected Resource(s)
Please list the resources as a list, for example:
- datadog_integration_pagerduty
- datadog_integration_pagerduty_service_object

### Terraform Configuration Files
```hcl
resource "datadog_integration_pagerduty" "pd" {
  subdomain           = "playhq"
  individual_services = true
  api_token           = data.aws_ssm_parameter.token.value
}

resource "datadog_integration_pagerduty_service_object" "events" {
  depends_on = [
    datadog_integration_pagerduty.pd
  ]
  service_name = "events"
  service_key  = "[service key]"
}
```

### Expected Behavior
I would expect that the configured service object remains in place.

### Actual Behavior
The service object is deleted, leaving an inconsistent terraform state.

**Comment by bkabrda** [comment] 2019-08-28 09:13
Hey, thanks for the report! The deleted individual PD services issue seems to be a duplicate of #299 AFAICS, so I'll close it in favor of that issue. If the fix for #299 (hopefully pushed today and released in next version) doesn't help, feel free to reopen.

The fact that the `api_token` always makes plan non-empty is also unfortunate, but that's the effect of the DD API not returning the token in GET requests, so there's no way for us to detect if there was a drift or not and so we try to replace it every time. You could add the following to your config:

```
  lifecycle {
    ignore_changes = [
      api_token
    ]
  }
```

as described at https://www.terraform.io/docs/configuration/resources.html#ignore_changes

If this is a big problem for you, please let us know and we can try talking to hashicorp folks to see if there's a better way of solving this.

**Closed by bkabrda** 2019-08-28 09:13 UTC
