### ISSUE TITLE
alert window query arg must match trigger window monitor option

### ISSUE THREAD

**Issue by cohandv** [terraform-providers/terraform-provider-datadog#246] opened 2019-06-24 19:17 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.8
+ provider.aws v2.16.0
+ provider.datadog v2.0.1
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)
- datadog_monitor

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Documentation states that the parameter is optional: https://www.terraform.io/docs/providers/datadog/r/monitor.html#trigger_window

**Comment by cohandv** [comment] 2019-06-24 19:18
[terraform.txt](https://github.com/terraform-providers/terraform-provider-datadog/files/3322240/terraform.txt)

Output of debug attached

**Comment by nmuesch** [comment] 2019-06-27 23:26
Hey @cohandv Thanks for the issue report. Could you share the terraform config you are using to trigger this behavior? For anomaly monitors, the trigger_window is required for anomaly monitors (I'm working on updating the docs to reflect that) 

If the issue is solely with the documentation, I'll share here when thats updated 😄

**Comment by cohandv** [comment] 2019-06-29 17:12
Hi @nmuesch thanks for replying, if this is the new behaviour, it's ok, I've been using this plugin with anomaly monitors at least from a year ago, and changed from version 1.9 and above. What I feel it's wrong is that the error is incorrect, if the argument is mandatory, it should say that, instead of failing when trying to create because it has assumed a value which is less than the one provided in the query.

**Comment by nmuesch** [comment] 2019-08-13 14:58
Hey @cohandv apologies for the delay here. I agree this can definitely be confusing. The issue we have is that this field is only required for certain monitor types, so it's not something we can mark as required in the terraform schema, otherwise it would be considered required for all monitor types. 

We recently updated the documentation to try to clarify this a bit - https://github.com/terraform-providers/terraform-provider-datadog/pull/252. I'll go ahead and close this issue for now but open to any feedback/suggestions. Thanks again and apologies for the troubles!

**Closed by nmuesch** 2019-08-13 14:58 UTC
